Gui.windows
sofa-framework/SofaGLFW pull request #109
Opened 2024-05-03 11:49 UTC by lamriaimen

2024-05-03 12:09 UTC, lamriaimen commented
[build-and-test-with-imgui]

2024-05-07 12:50 UTC, alxbilger requested changes
Nice! I requested minor changes though

2024-05-07 12:50 UTC, alxbilger commented on SofaImGui/src/SofaImGui/AppIniFile.cpp
> +#include "windows/Settings.h"
Too much included files. Try to reduce them to the minimum. Unnecessary includes pollutes the code and increase the compilation time. Do it also in the other files that you introduced

2024-05-07 12:50 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Components.h
> +    };
I don't recommend a design based on a class for such a simple thing. You can implement a free function in the `Components` namespace. For example:

```cpp
namespace Components
{
    void showComponents(const char* const& windowNameComponents, bool& isComponentsWindowOpen);
}
```

However, in SOFA we try to keep a match between the namespaces and the folder structure. In this case, I would suggest

```cpp
namespace windows
{
    void showComponents(const char* const& windowNameComponents, bool& isComponentsWindowOpen);
}
```

which means that you will have to call it with `windows::showComponents(....)`.

Also add a brief doxygen comment to describe the function.

2024-05-07 14:29 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Components.h
> +    };
@lamriaimen my comment applies for all your similar class in the windows folder

2024-05-07 14:36 UTC, lamriaimen commented on SofaImGui/src/SofaImGui/windows/Components.h
> +    };
@alxbilger  for the adding doxygen comment part or also making them all free functions in the windows  namespace

2024-05-07 14:37 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Components.h
> +    };
Both please

2024-05-13 12:12 UTC, alxbilger requested changes

2024-05-13 12:12 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/DisplayFlags.h
> +/**
Move the doxygen comment just above the function. I don't think it's valid otherwise. Do that in all functions you introduced

2024-05-17 08:39 UTC, alxbilger requested changes
Almost good to go

2024-05-17 08:39 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Components.h
> +
```suggestion
```
Remove the blank lines between the doxygen comments and the function. Just to be sure that it won't affect the doxygen generation (which is not enabled for now). Also in the other files

2024-05-17 08:39 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Components.h
> +                             , bool& isComponentsWindowOpen);
```suggestion
         void showComponents(const char* const& windowNameComponents,
                             bool& isComponentsWindowOpen);
```
Cosmetic: the comas at the end of the line. Also in the other files

2024-05-17 09:34 UTC, alxbilger approved these changes

2024-05-17 09:34 UTC, merged