[SofaImGui] Fix window positioning and state persistence issues
sofa-framework/SofaGLFW pull request #111
Opened 2024-05-17 15:15 UTC by lamriaimen

- Implemented mechanism to persist window positions and states across application runs.
- Inject `first_run.txt` in the `builder/bin` folder once first run is completed.
- Added file check for `first_run.txt` to  set ImGui docking data just in the first run.
- Fixed issue with window positions not being saved, ensuring they remain in place across sessions.
- Resolved lag issue with windows not being properly pinned due to size differences with the interface.

2024-05-21 07:40 UTC, alxbilger requested changes
You designed `WindowsManager` to be a class, but you don't use instances of this class properly. For example, you don't use the same instance in ImGuiGUIEngine.cpp and in Components.cpp.
But the good news is that `WindowsManager` does not need to be a class. Indeed, it does not store anything internally. I suggest to create only free functions in the namespace `windows`.

I also would like to know if the .ini file created by imgui does not store also the state of a window (open or close). Just wanted to know if you really need to store it by yourself using `checkIfWindowFileExist`.

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/CMakeLists.txt
> +    set(SOFAGLFWIMGUI_FORCE_OPENGL2 ON CACHE BOOL "" FORCE)
I don't think this line must be part of this PR. It has been changed in another PR https://github.com/sofa-framework/SofaGLFW/pull/110, and this PR is not about OpenGL or macOS.

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +        static bool isLogWindowOpen = true;
What is the purpose of the 3 static boolean variables in this scope?

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +        m_currentFBOSize = {50, 50};
Can you explain why you changed the values here?

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.h
> +#include "windows/WindowsManager.h"
I am not sure you need to include this file in the header. Can you include it only in the cpp file?

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Components.cpp
> +    extern WindowsManager winManager;
```suggestion
    WindowsManager winManager;
```

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/WindowsManager.cpp
> +                std::cerr << "Error deleting " << windowType << ".txt" << std::endl;
```suggestion
                msg_error("WindowsManager") << "Error deleting " << windowType << ".txt";
```

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/WindowsManager.cpp
> +        if (checkIfWindowFileExist(windowType)) {
[Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style) please. Curly brace on the next line

2024-05-21 07:40 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/WindowsManager.cpp
> +            if (remove((windowType + ".txt").c_str()) != 0) {
```suggestion
            if (std::remove((windowType + ".txt").c_str()) != 0) {
```
Explicit the use of `std` namespace

2024-05-21 13:24 UTC, lamriaimen commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.h
> +#include "windows/WindowsManager.h"
because I wrote "using windows::WindowsManager " in the .h file

2024-05-21 13:24 UTC, lamriaimen commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +        m_currentFBOSize = {50, 50};
Well i guess it was when i was trying to see the implications it has on the windows (will change it back in the next commit)

2024-05-21 13:24 UTC, lamriaimen commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +        static bool isLogWindowOpen = true;
Those three variables are inside the block of code that will only be executed the first time you compile and run SOFA with ImGui. After that, even if you compile it again, the block of code won't be executed. The purpose of putting them there is for the first time to have the viewport, scene graph, and log window open (default preferences)

2024-05-22 13:00 UTC, alxbilger requested changes

2024-05-22 13:00 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +        winManagerLog.setState(true);
```suggestion
        winManagerViewPort.setState(true);
        winManagerSceneGraph.setState(true);
        winManagerLog.setState(true);
```
I still think that those static variables are useless in this scope. Could you try?

2024-05-22 13:00 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Profiler.cpp
>  #include <imgui_internal.h> //imgui_internal.h is included in order to use the DockspaceBuilder API (which is still in development)
you changed the format of the file. It's difficult to review as the true differences are mixed with format changes. Could you revert the format changes only?

2024-05-22 13:00 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/ViewPort.cpp
> +    extern WindowState winManager;
```suggestion
```

2024-05-22 13:00 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/WindowsManager.h
> +    public:
```suggestion
    class WindowState
    {
    public:
```

2024-05-22 13:00 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/WindowsManager.h
> +    public:
If the class is called WindowState, it must go in a file called WindowState

2024-05-22 13:00 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/Plugins.cpp
> +
```suggestion
```

2024-05-22 13:00 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +            winManagerViewPort.setState(isViewportWindowOpen);
```suggestion
            ImGui::Checkbox(windowNameViewport, &winManagerViewPort.getState());
```

With a bit of changes, you should be able to write something like this, i.e. the state is used directly by ImGui widgets. In that case, the static variables (such as `isPerformancesWindowOpen`...) are no longer necessary.

2024-05-23 11:21 UTC, alxbilger requested changes

2024-05-23 11:21 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +    WindowState firstRunState("firstrun.txt");
I recommend to define them as class members of `ImGuiGUIEngine`

2024-05-28 09:48 UTC, lamriaimen commented
This Pr needs [https://github.com/sofa-framework/SofaGLFW/pull/113](url) to be merged before It merges

2024-06-05 07:35 UTC, lamriaimen commented
@alxbilger  https://github.com/sofa-framework/SofaGLFW/pull/114 didn't fix the problem of the non  destructor call

2024-06-05 12:35 UTC, alxbilger commented
> @alxbilger #114 didn't fix the problem of the non destructor call

Can you try again with https://github.com/sofa-framework/SofaGLFW/pull/117 now? It works on my computer.

2024-06-05 13:01 UTC, lamriaimen commented
@alxbilger it's working. the Pr https://github.com/sofa-framework/SofaGLFW/pull/117 fixes the problem and it needs to be merged before this one as you recommended.

2024-06-25 10:31 UTC, alxbilger approved these changes

2024-06-25 10:31 UTC, merged