[ImGui] Put config files into a folder
sofa-framework/SofaGLFW pull request #121
Opened 2024-08-01 00:10 UTC by fredroy

for less "pollution" in the working dir

2024-08-01 08:49 UTC, alxbilger reviewed
Should we wait for https://github.com/sofa-framework/sofa/pull/4875 to put the config files in the config folder?

2024-08-01 10:20 UTC, fredroy commented
> Should we wait for [sofa-framework/sofa#4875](https://github.com/sofa-framework/sofa/pull/4875) to put the config files in the config folder?

Akshually 🤓 that was my first intention but I discovered the static function in BaseGui called setConfigDirectoryPath() which set globally the config dir so I wont use the function introduced in #4875 (in SofaGLFW at least)

2024-08-02 08:07 UTC, alxbilger commented
So you want to use `BaseGUI::getConfigDirectoryPath()`?

2024-08-06 07:33 UTC, alxbilger requested changes

2024-08-06 07:33 UTC, alxbilger commented on SofaImGui/src/SofaImGui/AppIniFile.cpp
> +        static const std::string configPath = sofa::gui::common::BaseGUI::getConfigDirectoryPath() + "/imgui";
```suggestion
        static const std::string configPath = helper::system::FileSystem::append(sofa::gui::common::BaseGUI::getConfigDirectoryPath(), "imgui");
```
To ensure only one slash separator.

2024-08-06 07:33 UTC, alxbilger commented on SofaImGui/src/SofaImGui/AppIniFile.cpp
> +        static const std::string appIniFile(getConfigurationFolderPath() + "/settings.ini");
```suggestion
        static const std::string appIniFile(helper::system::FileSystem::append(getConfigurationFolderPath(), "settings.ini"));
```

2024-08-06 07:33 UTC, alxbilger commented on SofaImGui/src/SofaImGui/AppIniFile.cpp
> +        static const std::string appIniFile(getConfigurationFolderPath() + "/settings.ini");
And also in ImGuiGUIEngine.cpp

2024-08-06 07:33 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/WindowState.cpp
> +        if (!std::filesystem::exists(p.parent_path()))
```suggestion
        if (!FileSystem::exists(p.parent_path()))
```

2024-08-06 07:33 UTC, alxbilger commented on SofaImGui/src/SofaImGui/windows/WindowState.cpp
> +            if (!std::filesystem::create_directories(p.parent_path()))
```suggestion
            if (!FileSystem::createDirectory(p.parent_path()))
```

2024-08-07 07:55 UTC, alxbilger approved these changes

2024-08-07 07:58 UTC, merged