[ImGui] Add "Reset View" Option to Restore Default Windows Positions
sofa-framework/SofaGLFW pull request #125
Opened 2024-08-05 15:21 UTC by lamriaimen

When users modify the pinned position of the windows in the interface, they may find it difficult to return to the original default view. This PR introduces a new "Reset View" option in the ImGui menu. Clicking this option will restore the window positions to their default state. The reset action is seamless, preserving all current data and avoiding the need to restart the interface. This enhancement simplifies the process of returning to the initial layout and improves user experience.

The window layout has been customized and is not in its default state. Users might struggle to return to this layout.

![Screenshot from 2024-08-05 17-13-58](https://github.com/user-attachments/assets/3485b7d7-964b-4dac-b794-a737064b813c)

After clicking the "Reset View" option, the window layout has been restored to its default position, making it easy to return to the original view without losing any data.

![Screenshot from 2024-08-05 17-14-11](https://github.com/user-attachments/assets/90f851fc-1929-4ac4-9adc-92d671b78592)

The "Reset View" option:
![Screenshot from 2024-08-05 17-20-35](https://github.com/user-attachments/assets/4e484415-2d8d-432a-9eda-5a4b88d83de2)

2024-08-06 00:19 UTC, fredroy requested changes
👍 

Small change: "Reset View" is a bit misleading, it is a bit confusion with the camera view I think.
I would name it "Reset UI Layout" or something like that

2024-08-06 00:19 UTC, fredroy commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +             }
```suggestion
            if (ImGui::MenuItem(ICON_FA_REFRESH  "  Reset View"))
            {
                resetView(dockspace_id,windowNameSceneGraph,windowNameLog,windowNameViewport);
            }
```

2024-08-06 00:19 UTC, fredroy commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +             }
biggest suggestion ever 😅

2024-08-06 07:26 UTC, alxbilger commented
> 👍
> 
> Small change: "Reset View" is a bit misleading with the camera view I think. I would name it "Reset UI Layout" or something like that

I agree with this suggestion

2024-08-06 07:29 UTC, alxbilger requested changes
Minor cosmetic changes requested. Otherwise 👍

2024-08-06 07:29 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +        resetView(dockspace_id,windowNameSceneGraph,windowNameLog,windowNameViewport);
```suggestion
        resetView(dockspace_id, windowNameSceneGraph, windowNameLog, windowNameViewport);
```

2024-08-06 07:29 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +void ImGuiGUIEngine::resetView(ImGuiID dockspace_id, const char* windowNameSceneGraph, const char *windowNameLog, const char *windowNameViewport) {
```suggestion
void ImGuiGUIEngine::resetView(ImGuiID dockspace_id, const char* windowNameSceneGraph, const char *windowNameLog, const char *windowNameViewport)
{
```

2024-08-06 07:29 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +}
```suggestion
}

```

2024-08-06 14:46 UTC, alxbilger approved these changes

2024-08-07 00:20 UTC, fredroy approved these changes

2024-08-07 00:20 UTC, merged