Change the selected monitor when toggling fullscreen to the current one
sofa-framework/SofaGLFW pull request #16
Opened 2022-03-16 21:19 UTC by BrunoB81HK

Currently, when toggling to fullscreen, the fullscreen happens on the primary monitor. This may not be the desired behavior when working with multiple monitors. I added a method to the `SofaGLFWBaseGUI` to retrieve the monitor on which the current window is. The solution was taken from this [question](https://stackoverflow.com/questions/21421074/how-to-create-a-full-screen-window-on-the-current-monitor-with-glfw).

2022-03-17 07:12 UTC, alxbilger requested changes
That's a very useful feature. Thanks for your contribution!
I just have minor requests.

2022-03-17 07:12 UTC, alxbilger commented on lib/src/SofaGLFW/SofaGLFWBaseGUI.cpp
> +    auto mini = [](int x, int y){ return x < y ? x : y; };
You could use `std::min` and `std::max` instead

2022-03-17 07:12 UTC, alxbilger commented on lib/src/SofaGLFW/SofaGLFWBaseGUI.cpp
> +    int num_monitors, i;
See https://www.sofa-framework.org/community/doc/programming-with-sofa/guidelines/ to learn the coding style used in SOFA. For variable names, we use lower Came case.

2022-03-18 07:44 UTC, alxbilger approved these changes

2022-03-18 07:58 UTC, fredroy approved these changes

2022-03-18 07:58 UTC, merged