Add save/restore camera parameters from file
sofa-framework/SofaGLFW pull request #62
Opened 2022-12-14 01:11 UTC by fredroy

and change (add) icons for "center camera".

![Screenshot 2022-12-14 100948](https://user-images.githubusercontent.com/11028016/207480277-92110036-a70c-48da-85c2-2a701d8dbb4d.png)

Question: should the camera be restored (if the .view file is present) at start-up like the other GUIs ?

2022-12-14 10:22 UTC, alxbilger requested changes

2022-12-14 10:22 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +            ImGui::Separator();
I would remove the separators, but not mandatory

2022-12-14 10:22 UTC, alxbilger commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +            if (ImGui::MenuItem(ICON_FA_CAMERA ICON_FA_ARROW_LEFT"  Restore Camera"))
It could be greyed out if the file does not exist

2022-12-19 02:38 UTC, fredroy commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +            ImGui::Separator();
done

2022-12-19 02:38 UTC, fredroy commented on SofaImGui/src/SofaImGui/ImGuiGUIEngine.cpp
> +            if (ImGui::MenuItem(ICON_FA_CAMERA ICON_FA_ARROW_LEFT"  Restore Camera"))
done too

2023-01-11 10:27 UTC, alxbilger approved these changes

2023-01-11 10:27 UTC, merged